language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh r_binary_install colorspace RColorBrewer dichromat munsell labeling SparseM Formula sp mvtnorm TH.data sandwich truncnorm gamlss.data quadprog gtable scales proto quantreg Hmisc mapproj maps hexbin maptools multcomp Rsolnp gamlss gamlss.dist pracma coda chron DAAG fts its mondate strucchange timeDate timeSeries tis tseries xts latticeExtra reshape2 depmixS4 signal Rmisc
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

secure: "Q4mMU7385U8+edjyB8GfksHi4WH4eWI4VE4yzgriXCSdDqyTyICiwzmgCCwE348vx2nVBdl3rRbH3LiIvJYMlh0FmMWIqaEy0f8+c+ZvQ1hb+ynBGKLgdxNW/MhEHX+Qb6LFyemDirDlS5pbrREOYsDPBGz8JvdC45BPzAIXFlA="

before_deploy:
  - ./travis-tool.sh install_github ryanhope/staticdocs
  - R -e "require(staticdocs); build_package('.','inst/web')"

after_success:
- .utility/initiate-publish.sh